---
- hosts: all
  become: true
  tasks:
  - name: Install repo on CentOS.
    shell: |
      rpm -Uvh --force https://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-agent-5.0.1-1.el8.x86_64.rpm
    when:     
     ansible_os_family == "RedHat"

  - name: Install repo on Ubuntu.
    shell: |
      wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1%2Bfocal_all.deb
      dpkg -i zabbix-release_5.0-1%2focal_all.deb
      apt update
    when:
     ansible_os_family == "Debian"

  - name: Install zabbix-agent on RHEL
    yum:
     name=zabbix-agent
    when:
     ansible_os_family == "RedHat"

  - name: Install zabbix-agent on Ubuntu
    apt:
     name: zabbix-agent
    when:
     ansible_os_family == "Debian"

  - name: Changing zabbix_agentd.conf == Server ==
    lineinfile:
     path: /etc/zabbix/zabbix_agentd.conf
     regexp: Server=127.0.0.1
     line: Server=178.154.215.237

  - name: Changing zabbix_agentd.conf == ServerActive ==
    lineinfile:
     path: /etc/zabbix/zabbix_agentd.conf
     regexp: ServerActive=127.0.0.1
     line: ServerActive=178.154.215.237

  - name: Changing Hostname on CentOS
    lineinfile:
     path: /etc/zabbix/zabbix_agentd.conf
     regexp: Hostname=Zabbix server
     line: Hostname=centos.my
    when:
     ansible_os_family == "RedHat"

  - name: Changing Hostname on Ubuntu server
    lineinfile:
     path: /etc/zabbix/zabbix_agentd.conf
     regexp: Hostname=Zabbix server
     line: Hostname=ubuntu.my
    when:
     ansible_os_family == "Debian"

  - name: reload zabbix-agent
    service: name=zabbix-agent state=restarted enabled=true
